SEASON_ID = "2025-26"
INITIAL_BUDGET = 5_000_000
MAX_PLAYERS = 10
MAX_PER_REAL_TEAM = 2
MAX_TOTAL_CHANGES = 150
MIN_BY_POSITION = {
    "BASE": 2,
    "ALERO": 3,
    "PIVOT": 3
}
ALL_POSITIONS = tuple(MIN_BY_POSITION.keys())
